stages:
  fetch_aqi_data:
    cmd: python -m src.data_gathering.aqi_data
    deps:
      - src/data_gathering/aqi_data.py
      - src/city_info.py
      - params.yaml
    outs:
      - data/raw/aqi_data.csv

  fetch_weather_data:
    cmd: python -m src.data_gathering.weather_data
    deps:
      - src/data_gathering/weather_data.py
      - src/city_info.py
      - params.yaml
    outs:
      - data/raw/weather_data.csv

  preprocess_data:
    cmd: python -m src.data_preprocessing.preprocessing
    deps:
      - src/data_preprocessing/preprocessing.py
      - data/raw/aqi_data.csv
      - data/raw/weather_data.csv
    outs:
      - data/interim/merged_data.csv

  feature_engineering:
    cmd: python -m src.feature_engineering.build_features
    deps:
      - src/feature_engineering/build_features.py
      - src/feature_engineering/temporal_features.py
      - src/feature_engineering/region.py
      - src/feature_engineering/city_to_region.py
      - src/feature_engineering/weather_features.py
      - src/city_info.py
      - data/interim/merged_data.csv
    outs:
      - data/processed/engineered_features.csv
  predictor_train_pm25_model:
    cmd: python -m src.model_building.predictor.pm25_model.pm25_predictor
    deps:
      - params.yaml
      - src/model_building/predictor/common/metrics.py
      - src/model_building/predictor/pm25_model/train_model.py
      - src/model_building/predictor/pm25_model/pm25_predictor.py
      - src/model_building/predictor/pm25_model/split_data.py
      - src/model_building/predictor/pm25_model/runtime_features.py
      - data/processed/engineered_features.csv
    outs:
      - src/model_building/predictor/pm25_model/pm25_predictor.pkl
    metrics:
      - metrics/predictor/pm25_metrics.json
  predictor_train_pm10_model:
    cmd: python -m src.model_building.predictor.pm10_model.pm10_predictor
    deps:
      - params.yaml
      - src/model_building/predictor/common/metrics.py
      - src/model_building/predictor/pm10_model/train_model.py
      - src/model_building/predictor/pm10_model/pm10_predictor.py
      - src/model_building/predictor/pm10_model/split_data.py
      - src/model_building/predictor/pm10_model/runtime_features.py
      - data/processed/engineered_features.csv
    outs:
      - src/model_building/predictor/pm10_model/pm10_predictor.pkl
    metrics:
      - metrics/predictor/pm10_metrics.json
  forecaster_train_pm25_model:
    cmd: python -m src.model_building.forecaster.pm25_model.pm25_forecaster
    deps:
      - params.yaml
      - src/model_building/forecaster/pm25_model/train_model.py
      - src/model_building/forecaster/pm25_model/pm25_forecaster.py
      - src/model_building/forecaster/pm25_model/split_data.py
      - src/model_building/forecaster/pm25_model/runtime_features.py
      - data/processed/engineered_features.csv
    outs:
      - models/pm25_forecaster.pkl
  forecaster_train_pm10_model:
    cmd: python -m src.model_building.forecaster.pm10_model.pm10_forecaster
    deps:
      - params.yaml
      - src/model_building/forecaster/pm10_model/train_model.py
      - src/model_building/forecaster/pm10_model/pm10_forecaster.py
      - src/model_building/forecaster/pm10_model/split_data.py
      - src/model_building/forecaster/pm10_model/runtime_features.py
      - data/processed/engineered_features.csv
    outs:
      - models/pm10_forecaster.pkl
    