stages:
  fetch_aqi_data:
    cmd: python src/data-gathering/aqi_data.py
    deps:
      - src/data-gathering/aqi_data.py
      - src/data-gathering/cities.py
      - params.yaml
    outs:
      - data/raw/aqi_data.csv
  fetch_weather_data:
    cmd: python src/data-gathering/weather_data.py
    deps:
      - src/data-gathering/weather_data.py
      - src/data-gathering/cities.py
      - params.yaml
    outs:
      - data/raw/weather_data.csv
  preprocess_data:
    cmd: python src/data-preprocessing/preprocessing.py
    deps:
      - src/data-preprocessing/preprocessing.py
      - data/raw/aqi_data.csv
      - data/raw/weather_data.csv
    outs:
      - data/interim/merged_data.csv
  feature_engineering:
    cmd: python src/feature_engineering/build_features.py
    deps:
      - src/feature_engineering/build_features.py
      - src/feature_engineering/temporal_features.py
      - src/feature_engineering/region.py
      - src/feature_engineering/city_to_region.py
      - src/feature_engineering/weather_features.py
      - data/interim/merged_data.csv
    outs:
      - data/processed/engineered_features.csv