data-gathering:
  start-date: 2023-06-30
  end-date: 2026-06-30
pm25_predictor:
  model-type: "XGBoost Regressor"
  hyperparameters:
    n_estimators: 925     
    max_depth: 8             
    learning_rate: 0.028    # Slower, more stable learning
    subsample: 0.95            
    colsample_bytree: 0.95    
    min_child_weight: 8    # Increased to prevent highly specific splits
    reg_alpha: 0.5            # L1 Regularization (Lasso)
    reg_lambda: 15.0           # L2 Regularization (Ridge)
    objective: reg:squarederror
    random_state: 42 
    #early_stopping_rounds: 80  
pm10_predictor:
  model-type: "XGBoost Regressor"
  hyperparameters:
    n_estimators: 900     
    max_depth: 8              
    learning_rate: 0.04    # Slower, more stable learning
    subsample: 1.0            
    colsample_bytree: 1.0    
    min_child_weight: 15   # Increased to prevent highly specific splits
    reg_alpha: 0.5            # L1 Regularization (Lasso)
    reg_lambda: 10          # L2 Regularization (Ridge)
    objective: reg:squarederror
    random_state: 42  # Enable categorical feature support
pm25_forecaster_t:
  model-type: "XGBoost Regressor"
  hyperparameters:
    n_estimators: 700     
    max_depth: 3           
    learning_rate: 0.01    # Slower, more stable learning
    subsample: 0.65            
    colsample_bytree: 0.65   
    min_child_weight: 15   # Increased to prevent highly specific splits
    reg_alpha: 0.5            # L1 Regularization (Lasso)
    reg_lambda: 15.0           # L2 Regularization (Ridge)
    objective: reg:squarederror
    random_state: 42
pm25_forecaster_t12:
  model-type: "XGBoost Regressor"
  hyperparameters:
    n_estimators: 900  
    max_depth: 3             
    learning_rate: 0.01 # Slower, more stable learning
    subsample: 0.7           
    colsample_bytree: 0.7  
    min_child_weight: 8   # Increased to prevent highly specific splits
    reg_alpha: 0.5            # L1 Regularization (Lasso)
    reg_lambda: 10.0           # L2 Regularization (Ridge)
    objective: "reg:squarederror"
    random_state: 42
pm25_forecaster_t24:
  model-type: "XGBoost Regressor"
  hyperparameters:
    n_estimators: 900  
    max_depth: 4           
    learning_rate: 0.01 # Slower, more stable learning
    subsample: 0.9           
    colsample_bytree: 0.9  
    min_child_weight: 10   # Increased to prevent highly specific splits
    reg_alpha: 0.5            # L1 Regularization (Lasso)
    reg_lambda: 10.0           # L2 Regularization (Ridge)
    objective: "reg:squarederror"
    random_state: 42
pm25_forecaster_t48:
  model-type: "XGBoost Regressor"
  hyperparameters:
    n_estimators: 900 
    max_depth: 3           
    learning_rate: 0.01 # Slower, more stable learning
    subsample: 0.9           
    colsample_bytree: 0.9  
    min_child_weight: 10   # Increased to prevent highly specific splits
    reg_alpha: 0.5            # L1 Regularization (Lasso)
    reg_lambda: 10.0           # L2 Regularization (Ridge)
    objective: "reg:squarederror"
    random_state: 42
pm10_forecaster_t:
  model-type: "XGBoost Regressor"
  hyperparameters:
    n_estimators: 850     
    max_depth: 3              
    learning_rate: 0.01    # Slower, more stable learning
    subsample: 0.7            
    colsample_bytree: 0.7    
    min_child_weight: 8   # Increased to prevent highly specific splits
    reg_alpha: 0.5            # L1 Regularization (Lasso)
    reg_lambda: 10.0          # L2 Regularization (Ridge)
    objective: reg:squarederror
    random_state: 42  # Enable categorical feature support