[project]
name = "aero-metrics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.141.1",
    "google-genai>=2.20.0",
    "joblib>=1.5.3",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "psycopg2>=2.9.12",
    "psycopg2-binary>=2.9.12",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
    "shap>=0.52.0",
    "sqlalchemy>=2.0.52",
    "uvicorn>=0.52.4",
    "xgboost>=3.4.1",
]
